import type { Metadata } from "next";
/* import { Geist, Geist_Mono } from "next/font/google"; */
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
/* 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
}); */

/* const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export async function generateMetadata() {
  return {
    title: {
      default: "Revelaciones de caro",
      template: "%s -Revelaciones de caro",
    },
    description: "Blog de Filosofía y Astrología",
    openGraph: {
      title: "Revelaciones de caro",
      description: "Blog de Filosofía y Astrología",
      images: [
        {
          url: "https://firebasestorage.googleapis.com/v0/b/blog-ca662.appspot.com/o/perfil.jpg?alt=media&token=42a2a5d7-f5b6-4b9b-b511-8b04b699354d",
          width: 800,
          height: 600,
          alt: "",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      site: "",
      creator: "Revelaciones de caro",
      title: "Revelaciones de caro",
      description: "DBlog de Filosofía y Astrología",
      images: [
        {
          url: "https://firebasestorage.googleapis.com/v0/b/blog-ca662.appspot.com/o/perfil.jpg?alt=media&token=42a2a5d7-f5b6-4b9b-b511-8b04b699354d",
          alt: "IMAGEN CARO ",
        },
      ],
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
